services:
  db:
    image: postgres:16-alpine
    container_name: kalender-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendar_xp
      TZ: Europe/Zurich
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - kalnet

  backend:
    build:
      context: ./backend
    container_name: kalender-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/calendar_xp
      BACKEND_CORS_ORIGINS: '["http://localhost", "http://orgalifer.ch", "https://orgalifer.ch", "http://192.168.1.136:8080"]'
      TZ: Europe/Zurich
    expose:
      - "8000"
    networks:
      - kalnet

  frontend:
    build:
      context: ./frontend
    container_name: kalender-frontend
    depends_on:
      - backend
    expose:
      - "80"
    networks:
      - kalnet

  nginx:
    image: nginx:latest
    container_name: kalender-nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - kalnet

networks:
  kalnet:
    driver: bridge
