services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendar_xp
      TZ: Europe/Zurich
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - kalnet

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/calendar_xp
      BACKEND_CORS_ORIGINS: '["http://orgalifer.ch", "https://orgalifer.ch", "http://localhost"]'
      TZ: Europe/Zurich
    expose:
      - "8000"
    networks:
      - kalnet

  frontend:
    build: ./frontend
    expose:
      - "80"
    networks:
      - kalnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    networks:
      - kalnet

networks:
  kalnet:
    driver: bridge
