version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: kalender-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendar_xp
      TZ: Europe/Zurich
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  backend:
    build: ./backend
    container_name: kalender-backend
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/calendar_xp
      BACKEND_CORS_ORIGINS: '["https://orgalifer.ch","http://localhost:8080","http://192.168.1.136:8080"]'
      TZ: Europe/Zurich
    expose:
      - "8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: kalender-frontend
    environment:
      VITE_API_URL: "https://orgalifer.ch/api"
      TZ: Europe/Zurich
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: kalender-nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    restart: always

  certbot:
    image: certbot/certbot
    container_name: kalender-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h; done"
