import { existsSync, mkdirSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const rootDir = join(__dirname, "..");
const nodeModulesDir = join(rootDir, "node_modules");
const modules = [
  "@fullcalendar/daygrid/main.css",
  "@fullcalendar/timegrid/main.css",
  "@fullcalendar/list/main.css"
];

if (!existsSync(nodeModulesDir)) {
  console.warn(
    "⚠️  Skipping FullCalendar placeholder check because node_modules is missing. Run `npm install` first."
  );
  process.exit(0);
}

console.log("🧩 Checking FullCalendar style modules...");

for (const modulePath of modules) {
  const absolutePath = join(nodeModulesDir, modulePath);
  if (existsSync(absolutePath)) {
    continue;
  }

  const targetDir = dirname(absolutePath);
  mkdirSync(targetDir, { recursive: true });
  writeFileSync(
    absolutePath,
    "/* Autogenerated placeholder created by scripts/prebuild.js to avoid missing FullCalendar CSS during build. */\n"
  );
  console.warn(`\u26A0\uFE0F Created placeholder stylesheet for missing module: ${modulePath}`);
}
