server {
    listen 80;
    server_name orgalifer.ch www.orgalifer.ch 192.168.1.136;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
